class DataTypes:

    def isAt(self, var):
        types = {
            "bool":"at",
            "long":"at",
            "short":"at",
            "byte":"at",
            "char":"at",
            "enum":"at",
            "float":"at",
            "double":"at",
            "doubleAngle":"at",
            "doubleLinear":"at",
            "string":"dt",
            "stringArray":"dt",
            "compound":"at",
            "message":"at",
            "time":"at",
            "matrix":"dt",
            "fltMatrix":"at",
            "reflectanceRGB":"dt",
            "reflectance":"at",
            "spectrumRGB":"dt",
            "spectrum":"at",
            "float2":"dt",
            "float2":"at",
            "float3":"dt",
            "float3":"at",
            "double2":"dt",
            "double2":"at",
            "double3":"dt",
            "double3":"at",
            "long2":"dt",
            "long2":"at",
            "long3":"dt",
            "long3":"at",
            "short2":"dt",
            "short2":"at",
            "short3":"dt",
            "short3":"at",
            "doubleArray":"dt",
            "floatArray":"dt",
            "Int32Array":"dt",
            "vectorArray":"dt",
            "nurbsCurve":"dt",
            "nurbsSurface":"dt",
            "mesh":"dt",
            "lattice":"dt",
            "pointArray":"dt",
            }
        return types[var] is "at"
